export const abbrevs = [
  { "abbrev": "Gn", "title": "Gênesis" },
  { "abbrev": "Êx", "title": "Êxodo" },
  { "abbrev": "Lv", "title": "Levítico" },
  { "abbrev": "Nm", "title": "Números" },
  { "abbrev": "Dt", "title": "Deuteronômio" },
  { "abbrev": "Js", "title": "Josué" },
  { "abbrev": "Jz", "title": "Juízes" },
  { "abbrev": "Rt", "title": "Rute" },
  { "abbrev": "1Sm", "title": "1 Samuel" },
  { "abbrev": "2Sm", "title": "2 Samuel" },
  { "abbrev": "1Rs", "title": "1 Reis" },
  { "abbrev": "2Rs", "title": "2 Reis" },
  { "abbrev": "1Cr", "title": "1 Crônicas" },
  { "abbrev": "2Cr", "title": "2 Crônicas" },
  { "abbrev": "Ed", "title": "Esdras" },
  { "abbrev": "Ne", "title": "Neemias" },
  { "abbrev": "Et", "title": "Ester" },
  { "abbrev": "Jó", "title": "Jó" },
  { "abbrev": "Sl", "title": "Salmos" },
  { "abbrev": "Pv", "title": "Provérbios" },
  { "abbrev": "Ec", "title": "Eclesiastes" },
  { "abbrev": "Ct", "title": "Cânticos" },
  { "abbrev": "Is", "title": "Isaías" },
  { "abbrev": "Jr", "title": "Jeremias" },
  { "abbrev": "Lm", "title": "Lamentações de Jeremias" },
  { "abbrev": "Ez", "title": "Ezequiel" },
  { "abbrev": "Dn", "title": "Daniel" },
  { "abbrev": "Os", "title": "Oséias" },
  { "abbrev": "Jl", "title": "Joel" },
  { "abbrev": "Am", "title": "Amós" },
  { "abbrev": "Ob", "title": "Obadias" },
  { "abbrev": "Jn", "title": "Jonas" },
  { "abbrev": "Mq", "title": "Miquéias" },
  { "abbrev": "Na", "title": "Naum" },
  { "abbrev": "Hc", "title": "Habacuque" },
  { "abbrev": "Sf", "title": "Sofonias" },
  { "abbrev": "Ag", "title": "Ageu" },
  { "abbrev": "Zc", "title": "Zacarias" },
  { "abbrev": "Ml", "title": "Malaquias" },
  { "abbrev": "Mt", "title": "Mateus" },
  { "abbrev": "Mc", "title": "Marcos" },
  { "abbrev": "Lc", "title": "Lucas" },
  { "abbrev": "Jo", "title": "João" },
  { "abbrev": "At", "title": "Atos" },
  { "abbrev": "Rm", "title": "Romanos" },
  { "abbrev": "1Co", "title": "1 Coríntios" },
  { "abbrev": "2Co", "title": "2 Coríntios" },
  { "abbrev": "Gl", "title": "Gálatas" },
  { "abbrev": "Ef", "title": "Efésios" },
  { "abbrev": "Fp", "title": "Filipenses" },
  { "abbrev": "Cl", "title": "Colossenses" },
  { "abbrev": "1Ts", "title": "1 Tessalonicenses" },
  { "abbrev": "2Ts", "title": "2 Tessalonicenses" },
  { "abbrev": "1Tn", "title": "1 Timóteo" },
  { "abbrev": "2Tm", "title": "2 Timóteo" },
  { "abbrev": "Tt", "title": "Tito" },
  { "abbrev": "Fm", "title": "Filemom" },
  { "abbrev": "Hb", "title": "Hebreus" },
  { "abbrev": "Tg", "title": "Tiago" },
  { "abbrev": "1Pe", "title": "1 Pedro" },
  { "abbrev": "2Pe", "title": "2 Pedro" },
  { "abbrev": "1Jo", "title": "1 João" },
  { "abbrev": "2Jo", "title": "2 João" },
  { "abbrev": "3Jo", "title": "3 João" },
  { "abbrev": "Jd", "title": "Judas" },
  { "abbrev": "Ap", "title": "Apocalipse" }
]